### PR TITLE
 Adding new property to date range picker and fix date initial selection values

### PR DESCRIPTION
**Pull request by FadyMagdy**
- Adding new property "Single Date Picker" to date range picker type to allow users to select one date only.
- Fixing date initial selection values for:
 --> Date from initial selection
 --> Date toinitial selection
edit
view
[changesScreenshots.zip](https://github.com/ClimberAB/ClimberSelectionBar/files/1245557/changesScreenshots.zip)

### CODE REVIEW

**Comment by mickeg** [comment]
Hi and thanks for your PR. We will definately look into this. 
Since it's minified code I'm afraid we can't accept and merge this PR.

//Mikael

**Comment by FadyMagdy** [comment]
Good morning Mikael,

Any updates about the requested modifications?
Please let me know if you have any questions.

Regards,
Fady
________________________________

**Comment by MichaelClimber** [comment]
Hi Fady,
we have not prioritized that small feature yet but we do think it is a good idea. (The Qlik answer would be "it's on the roadmap")... We will let you know as soon as it is included.

**Comment by FadyMagdy** [comment]
Hi Michael,


Thank you for your feedback.


I need to apply this change and use the extension in a demo to my customer early next week. This customer has a process that vets extensions so my change cannot be just committed to a new branch.



I appreciate your feedback and please let me know if you have any questions about the change I applied.


Regards,

Fady

________________________________

**Comment by MichaelClimber** [comment]
Hi Fady,
I understand the situation. We will not prioritize this implementation before next week so it will not be released by us before then. However your small change seems to be working ok and we can not see that it should hurt the extension so you could just go ahead with the solution you created. Of course this means you would have to make the same change again when using an updated version of our extension.

If you have customers that use our extensions in critical applications or need specific changes we recommend that they contact us for a dialog around subscription for support. If they have the extensions supported through us (rather than just using our open source versions) they can also request to pay for changes that they prioritize higher than us but would still work well in the extension. (Just like this one :-)).

Kind regards

Michael

**Comment by FadyMagdy** [comment]
Hi Michael

Subscribing to support seems like a good idea. However, this is something our team would obtain directly from you, not through our customers.

Can you please give us some more details of the model of support you provide and how much it costs?

Thank you

________________________________

**Comment by MichaelClimber** [comment]
Hi Fady,
our subscriptions are offered direct to customers (owner of Qlik Server) with a monthly fee. Prices are based on  the number of tokens in the installation. We do not sell through, or to, Qlik partners at this time. 

Kind regards

Michael

**Comment by FadyMagdy** [comment]
Hi Michael,

OK, sorry but this will not work for our needs. We will continue to clone the extension for now until you incorporate the fix in the future.

Regards,
Fady
________________________________

**Pull request closed without merging**
